name: Build Artifact

on:
  push:
    branches: ["main"]

jobs:
  Build_Artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Artifact
        run: ./gradlew build

      - name: Rename Artifact
        run: mv build/libs/base-physics-simulation-1.0-SNAPSHOT.jar build/libs/base-physics-simulation.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'base-physics-simulation.jar'
          path: 'build/libs/base-physics-simulation.jar'